SimpleChatApp/Models/RoomViewModel.cs
namespace SimpleChatApp.Models
{
    public class RoomViewModel
    {
        public int RoomId { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsDefault { get; set; }
    }
}

SimpleChatApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SimpleChatApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SimpleChatApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleChatApp.Domain;

namespace SimpleChatApp.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public int GroupId { get; private set; }

        public void OnGet(int groupId)
        {
            GroupId = groupId;
        }
    }
}

SimpleChatApp/ViewComponents/ChatViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SimpleChatApp.Domain;

namespace SimpleChatApp.ViewComponents
{
    public class ChatViewComponent : ViewComponent
    {
        private readonly ChatHub _chatHub;

        public ChatViewComponent(ChatHub chatHub)
        {
            _chatHub = chatHub;
        }

        public IViewComponentResult Invoke(int roomId)
        {
            return View(_chatHub.GetLastMessages(roomId));
        }
    }
}

SimpleChatApp/ViewComponents/RoomListViewComponent.cs
using System.Collections.Immutable;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SimpleChatApp.Domain;
using SimpleChatApp.Models;

namespace SimpleChatApp.ViewComponents
{
    public class RoomListViewComponent : ViewComponent
    {
        private readonly ChatHub _chatHub;

        public RoomListViewComponent(ChatHub chatHub)
        {
            _chatHub = chatHub;
        }

        public IViewComponentResult Invoke()
        {
            var rooms = _chatHub.GetRooms().Select(r => new RoomViewModel
            {
                IsDefault = r.Value.IsDefault,
                IsAvailable = r.Value.IsAvailable,
                RoomId = r.Key
            }).ToImmutableList();
            
            return View(rooms);
        }
    }
}

SimpleChatApp/Pages/Components/Chat/Default.cshtml
@model IReadOnlyCollection<SimpleChatApp.Domain.Message>

<div class="row">
    <div id="message-box" class="col-md-12">
        @foreach (var message in Model)
        {
            <div>@message.AuthorName: @message.Content</div>
        }
    </div>
</div>
<div class="row">
    <input id="name-input" class="input-group-text col-md-2" placeholder="Name"/>
    <input id="text-input" class="input-group-text col-md" placeholder="Message"/>
    <div id="send-button" class="btn btn-dark col-md-3">Send</div>
</div>

SimpleChatApp/Pages/Components/RoomList/Default.cshtml
@model IReadOnlyCollection<SimpleChatApp.Models.RoomViewModel>
<div class="row">
    @foreach (var room in Model)
    {
        if (room.IsAvailable)
        {
            <a class="btn btn-info col-md"
               asp-page="/Index" 
               asp-route-groupId="@room.RoomId">Room #@room.RoomId</a>
        }
        else
        {
            <div class="btn badge-danger col-md">Room #@room.RoomId</div>
        }
    }
</div>

SimpleChatApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = $"Chat #{Model.GroupId}";
}
<h2>Room #@Model.GroupId</h2>

<vc:chat room-id="@Model.GroupId" />
<vc:room-list />

@section Scripts
{
    <script>
        groupId = '@Model.GroupId'
    </script>
}

SimpleChatApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleChatApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SimpleChatApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SimpleChatApp
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
</environment>
    @RenderSection("Scripts", required: false)
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>